//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1 {
	
	
	public partial class _Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lblUsername;
		
		protected System.Web.UI.WebControls.TextBox txtUserName;
		
		protected System.Web.UI.WebControls.Label lblPassword;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.Button btnUserLogin;
		
		protected System.Web.UI.WebControls.Label lblError;
		
		protected System.Web.UI.WebControls.ImageButton ImageButton1;
	}
}
