//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webtimeclockEntities : DbContext
    {
        public webtimeclockEntities()
            : base("name=webtimeclockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<activeuser> activeusers { get; set; }
        public DbSet<fcc> fccs { get; set; }
        public DbSet<shift> shifts { get; set; }
        public DbSet<user> users { get; set; }
    }
}
