//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class shift
{
    public int ShiftID { get; set; }
    public string UserID { get; set; }
    public System.DateTime Date { get; set; }
    public Nullable<System.DateTime> TimeIn { get; set; }
    public Nullable<System.DateTime> TimeOut { get; set; }
    public Nullable<System.TimeSpan> TimeWorked { get; set; }
    public Nullable<System.TimeSpan> RoundedTimeWorked { get; set; }
    public string Comments { get; set; }
}
